version: '3.8'

services:

  api-node:
    build: ./api-node
    container_name: api-node
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - JWT_SECRET=interseguro_secret_key
    networks:
      - interseguro-net
    restart: unless-stopped

  api-go:
    build: ./api-go
    container_name: api-go
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NODE_API_URL=http://api-node:4000
      - JWT_SECRET=interseguro_secret_key
    depends_on:
      - api-node
    networks:
      - interseguro-net
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:8080
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - api-go
    networks:
      - interseguro-net
    restart: unless-stopped

networks:
  interseguro-net:
    driver: bridge
